apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo1"
  annotations:
    github.com/project-slug: rdurgade/demo1
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: dev-demo1
    backstage.io/kubernetes-id: "demo1"
    sonarqube.org/project-key: "demo1"
    grafana/tag-selector: "kubernetes"
    prometheus.io/rule: container_cpu_usage_seconds_total{namespace="demo1"}
    prometheus.io/alert: all
  links:
    - url: https://demo1.example.com
      title: Website
      icon: Website
    - url: https://grafana.example.com/
      title: Dashboard
      icon: dashboard      
    - url: https://alerts.example.com/
      title: Alerts
      icon: alert 
    - url: https://argocd.example.com/applications/dev-demo1?resource=
      title: ArgoCD
      icon: cloud
  tags:
    - golang
    - "examples"
    - "service"
    - "experimental"
spec:
  system: "examples"
  type:  "service"
  lifecycle: "experimental"
  owner: "guests"
